In [1]:
import pandas as pd

In [2]:
# def get_mta_data(dates):
#     file_path_string = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_{}.txt'
#     dfs = []
#     for date in dates:
#         df = pd.read_csv(file_path_string.format(date))
#         dfs.append(df)
#     return pd.concat(dfs)

In [3]:
# df = get_mta_data(['200627', '200620'])
#Kaggle Data Sets
nyc_census_tracts = pd.read_csv('./data/nyc_census_tracts.csv')
census_block_loc = pd.read_csv('./data/census_block_loc.csv')
# Stations with Census Block ids and Census Tract ids
stations = pd.read_csv('./data/stations_with_tract_id.csv')

In [4]:
stations.head()

,Station ID,Complex ID,GTFS Stop ID,Division,Line,Stop Name,Borough,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,Census Block,Census Tract
0,1,1,R01,BMT,Astoria,Astoria - Ditmars Blvd,Q,N W,Elevated,40.775036,-73.912034,NaN,Manhattan,360810115002001,36081011500
1,2,2,R03,BMT,Astoria,Astoria Blvd,Q,N W,Elevated,40.770258,-73.917843,Ditmars Blvd,Manhattan,360810125001009,36081012500
2,3,3,R04,BMT,Astoria,30 Av,Q,N W,Elevated,40.766779,-73.921479,Astoria - Ditmars Blvd,Manhattan,360810063001001,36081006300
3,4,4,R05,BMT,Astoria,Broadway,Q,N W,Elevated,40.761820,-73.925508,Astoria - Ditmars Blvd,Manhattan,360810059003000,36081005900
4,5,5,R06,BMT,Astoria,36 Av,Q,N W,Elevated,40.756804,-73.929575,Astoria - Ditmars Blvd,Manhattan,360810053004002,36081005300

In [11]:
nyc_census_tracts['Total_Poverty'] = nyc_census_tracts['Poverty'].multiply(nyc_census_tracts['TotalPop']).multiply(1/100)
nyc_census_tracts.head()

,CensusTract,County,Borough,TotalPop,Men,Women,Hispanic,White,Black,Native,...,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment,Total_Poverty
0,36005000100,Bronx,Bronx,7703,7133,570,29.9,6.1,60.9,0.2,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
1,36005000200,Bronx,Bronx,5403,2659,2744,75.8,2.3,16.0,0.0,...,0.0,0.0,43.0,2308,80.8,16.2,2.9,0.0,7.7,1080.600
2,36005000400,Bronx,Bronx,5915,2896,3019,62.7,3.6,30.7,0.0,...,0.5,2.1,45.0,2675,71.7,25.3,2.5,0.6,9.5,780.780
3,36005001600,Bronx,Bronx,5879,2558,3321,65.1,1.6,32.4,0.0,...,1.6,1.7,38.8,2120,75.0,21.3,3.8,0.0,8.7,1546.177
4,36005001900,Bronx,Bronx,2591,1206,1385,55.4,9.0,29.0,0.0,...,2.4,6.2,45.4,1083,76.8,15.5,7.7,0.0,19.2,961.261

In [13]:
stations_with_census = pd.merge(stations,
                                nyc_census_tracts[['CensusTract', 'Poverty', 'TotalPop', 'Total_Poverty']],
                                left_on='Census Tract', 
                                right_on='CensusTract')

In [14]:
stations_with_census.sort_values('Total_Poverty', ascending=False).head(12)

,Station ID,Complex ID,GTFS Stop ID,Division,Line,Stop Name,Borough,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,Census Block,Census Tract,CensusTract,Poverty,TotalPop,Total_Poverty
269,234,234,F16,IND,6th Av - Culver,East Broadway,M,F,Subway,40.713715,-73.990173,Uptown & Queens,Brooklyn,360610006001001,36061000600,36061000600,44.7,12554,5611.638
192,156,156,A18,IND,8th Av - Fulton St,103 St,M,B C,Subway,40.796092,-73.961454,Uptown & The Bronx,Downtown & Brooklyn,360610189002000,36061018900,36061018900,36.0,12825,4617.000
166,135,135,L26,BMT,Canarsie,Livonia Av,Bk,L,Elevated,40.664038,-73.900571,Manhattan,Canarsie - Rockaway Parkway,360470910004004,36047091000,36047091000,67.3,6094,4101.262
167,349,349,254,IRT,Eastern Pky,Junius St,Bk,3,Elevated,40.663515,-73.902447,Manhattan,New Lots,360470910003000,36047091000,36047091000,67.3,6094,4101.262
402,383,383,408,IRT,Jerome Av,183 St,Bx,4,Elevated,40.858407,-73.903879,Woodlawn,Manhattan,360050239002001,36005023900,36005023900,45.2,8282,3743.464
165,134,134,L25,BMT,Canarsie,Sutter Av,Bk,L,Elevated,40.669367,-73.901975,Manhattan,Canarsie - Rockaway Parkway,360470908002000,36047090800,36047090800,62.1,5679,3526.659
448,441,441,227,IRT,Lenox - White Plains Rd,Central Park North (110 St),M,2 3,Subway,40.799075,-73.951822,Uptown & The Bronx,Downtown & Brooklyn,360610186002000,36061018600,36061018600,44.4,7310,3245.640
397,378,378,401,IRT,Jerome Av,Woodlawn,Bx,4,Elevated,40.886037,-73.878751,NaN,Manhattan,360050431004000,36005043100,36005043100,30.1,10325,3107.825
412,393,393,622,IRT,Lexington Av,116 St,M,6,Subway,40.798629,-73.941617,Uptown & The Bronx,Downtown,360610182001000,36061018200,36061018200,43.0,7206,3098.580
259,220,220,D12,IND,Concourse,155 St,M,B D,Subway,40.830135,-73.938209,The Bronx,Downtown & Brooklyn,360610243021005,36061024302,36061024302,42.6,7239,3083.814
260,221,221,B04,IND,63rd St,21 St - Queensbridge,Q,F,Subway,40.754203,-73.942836,Jamaica,Manhattan,360810025004000,36081002500,36081002500,48.2,6392,3080.944
342,306,306,116,IRT,Broadway - 7Av,125 St,M,1,Elevated,40.815581,-73.958372,Uptown & The Bronx,Downtown,360610211002000,36061021100,36061021100,29.5,10211,3012.245

In [8]:
stations.columns

Index(['Station ID', 'Complex ID', 'GTFS Stop ID', 'Division', 'Line',
       'Stop Name', 'Borough', 'Daytime Routes', 'Structure', 'GTFS Latitude',
       'GTFS Longitude', 'North Direction Label', 'South Direction Label',
       'Census Block', 'Census Tract'],
      dtype='object')